version: "3"
services:
  testduckdns:
    image: anujdatar/duckdns
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS_FILE=/run/secrets/duckdns_subdomains
      - TOKEN_FILE=/run/secrets/duckdns_token
      - TZ=America/New_York
      - RECORD_TYPE=AAAA
      - FREQUENCY=5
    secrets:
      - duckdns_subdomains
      - duckdns_token

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00::/64

secrets:
  duckdns_subdomains:
    file: duckdns_subdomains.txt
  duckdns_token:
    file: duckdns_token.txt
